Vagrant.configure("2") do |config|

  config.vm.provider :virtualbox do |v|
    v.memory = 512
  end

  config.vm.define "dbserver" do |db|
    db.vm.box = "ubuntu/xenial64"
    db.vm.hostname = "dbserver"
    db.vm.network :private_network, ip: "10.10.10.10"
    db.vm.provision "ansible" do |ansible|
      ansible.compatibility_mode = "2.0"
      ansible.playbook = "db.yml"
      ansible.groups = {
      "tag_db" => ["dbserver"],
      "tag_db:vars" => {
        "mongodb_bind_ip" => "0.0.0.0",
        }
      }
    end
  end

  config.vm.define "appserver" do |app|
    app.vm.box = "ubuntu/xenial64"
    app.vm.hostname = "appserver"
    app.vm.network :private_network, ip: "10.10.10.20"
    app.vm.provision "ansible" do |ansible|
      ansible.compatibility_mode = "2.0"
      ansible.playbook = "app.yml"
      ansible.groups = {
      "tag_app" => ["appserver"],
      "tag_app:vars" => {
        "reddit_app_user" => "ubuntu",
        "reddit_app_db_host" => "10.10.10.10",
        }
      }
    end
  end
end
